### ISSUE TITLE
SESSION_ATTACHED received during integration tests

### ISSUE THREAD

**Issue by wennmo** [qlik-oss/enigma-go#140] opened 2020-03-09 11:39 UTC
When running the examples in Circle CI we get sporadic failures due to attaching to existing sessions instead of creating a new session. We need to investigate why this occurs and how we can mitigate it.

Example:
https://circleci.com/gh/qlik-oss/enigma-go/791

**Comment by glooms** [comment] 2020-07-24 14:29
After some investigation I haven't been able to reproduce this behavior in any way where it shouldn't occur, meaning that it only occurs if two sessions using the exact same url are opened concurrently. This seems to be the case since at least engine 12.700.0, I will therefore close this issue.

**Closed by glooms** 2020-07-24 14:29 UTC
Labels: bug
